<a href="https://colab.research.google.com/github/ruthgrubio/math/blob/main/practicas/practica_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.1
**Determinante en Excel**  

* Cree un fichero en Excel de nombre algebra.xlsm.
* La extensión **xlsm** corresponde a los archivos de Excel habilitados para macros.
* Utilice la Hoja 1 para hacer la Práctica 3.1.
* Se pide:
 1. Cree una matriz cuadrada de dimensión 5×5, formada por números aleatorios enteros entre -9 y +9.
 2. Calcule el determinante de esta matriz
 3. Cree un programa en **VBA** que busque una matriz de este tipo cuyo determinante sea cero.
 4. Copie la matriz encontrada y péguela debajo con "pegado especial valores" para que no varíe su contenido al efectuar el recálculo manual de la hoja.

## Práctica 3.2
**Matriz inversa en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 2 para hacer la Práctica 3.2.
* Se pide:
 1. Crea la matriz $A$ que es una matriz cuadrada de dimensiones 5×5 usando números aleatorios enteros entre -9 y +9, excepto cero
 2. Calcule su determinante
 3. Calcule su transpuesta usando la función ```TRANSPONER```
 4. Calcule su matriz inversa $A^{-1}$
 5. Multiplique la matriz $A$ por su inversa $A^{-1}$ y compruebe que el producto es la matriz identidad.
 $$AA^{-1}=I$$

## Práctica 3.3
**Resolución de sistemas lineales en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 3 para hacer la Práctica 3.3.
* Se pide:
 1. Cree un sistema de 5 ecuaciones con 5 incógnitas con **solución única**.
 2. Una de las ecuaciones será: $\quad x_1+2x_2-x_3+x_4-3x_5=6$
 3. Muestre las ecuaciones del sistema usando el [editor de ecuaciones](https://support.microsoft.com/es-es/office/editor-de-ecuaciones-6eac7d71-3c74-437b-80d3-c7dea24fdf3f) de Excel. $\quad Ax=b$
 4. Monte la matriz $A$ del sistema de ecuaciones y la matriz $b$ con los términos independientes. Muestre ambas matrices.
 5. Calcule la matriz inversa $A^{-1}$
 6. Resuelva el sistema lineal de ecuaciones con este método: $\quad Ax=b \quad \Longrightarrow \quad x=A^{-1}b$
 7. Compruebe si el resultado obtenido es la solución del sistema de ecuaciones. Justifique esa comprobación.

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

In [15]:
from random import randint, choice

N = 3
M = 3

m = [[randint(1,9) * choice ([1, -1]) for j in range(M)] for i in range(N)]


for f in m:
    print(f)
    

     

[5, 3, 5]
[-4, -2, -6]
[-9, 6, -4]


In [18]:
import numpy as np

n = 3   # orden nxn de la matriz cuadrada

while True:
    m = np.random.randint(-9,10, size=(n, n))   # aleatorios enteros entre -9 y +9
    determ = np.linalg.det(m)
    if determ == 1:
        print(m)
        break

print(f"El determinante de la matriz es {determ}")
     

[[ 1  2  4]
 [-2 -3  6]
 [ 1  1 -9]]
El determinante de la matriz es 1.0


In [22]:
import numpy as np
m = np.array([[1,2,4],[-2,-3,6],[1,1,-9]])
print("Matriz:")
print(m)
print("\nTranspuesta:")
print(np.transpose(m))

Matriz:
[[ 1  2  4]
 [-2 -3  6]
 [ 1  1 -9]]

Transpuesta:
[[ 1 -2  1]
 [ 2 -3  1]
 [ 4  6 -9]]


In [23]:
print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()

Inversa:
[[ 21.  22.  24.]
 [-12. -13. -14.]
 [  1.   1.   1.]]



In [24]:
print("Matriz Identidad:")
identidad = np.dot(m, minv)   # multiplicación de matrices
print(identidad)
print()

Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [25]:
print("Matriz Identidad con valores enteros:")
print(identidad.astype(int))   # así forzamos a valores enteros
     

Matriz Identidad con valores enteros:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [26]:
from time import process_time

t1 = process_time()

for i in range(10_000_000):
    cuadrado = i**2

t2 = process_time()
print(f"El proceso ha tardado {t2-t1} segundos.")

El proceso ha tardado 3.269525182999999 segundos.


## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.
2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?

## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?